### ISSUE TITLE
webkit no animation

### ISSUE THREAD

**Issue by Retch** [beekai-oss/react-simple-animate#105]
**Describe the bug**
There is no animation played when trying this with webkit engine. With Chrome desktop it works fine.

**Smartphone:**
 - Device: [iPhoneXS]
 - OS: [iOS16.0]
 - Browser [chrome, safari]

**Comment by bluebill1049** [comment]
can you share a reproducible codesandbox?

**Comment by bluebill1049** [comment]
https://user-images.githubusercontent.com/10513364/187894170-3029d939-4d3a-4d24-bc0f-7ea26d48fab5.mov

working version with safari above
